parameters:
  kiboko.facebook_catalog.repository.product_attribute_value.broker.class: Kiboko\Component\MagentoDriver\Broker\ProductAttributeValueRepositoryBroker

  kiboko.facebook_catalog.factory.product.broker.class: Kiboko\Component\MagentoDriver\Broker\ProductFactoryBroker

services:
  kiboko.facebook_catalog.repository.product_attribute_value.broker:
    class: '%kiboko.facebook_catalog.repository.product_attribute_value.broker.class%'

  kiboko.facebook_catalog.factory.product.broker:
    class: '%kiboko.facebook_catalog.factory.product.broker.class%'