parameters:
  kiboko.facebook_catalog.backend.entity_attribute.table: 'eav_entity_attribute'
  kiboko.facebook_catalog.backend.entity_attribute.fields:
    - 'entity_attribute_id'
    - 'entity_type_id'
    - 'attribute_set_id'
    - 'attribute_group_id'
    - 'attribute_id'
    - 'sort_order'

  kiboko.facebook_catalog.backend.entity_type.table: 'eav_entity_type'
  kiboko.facebook_catalog.backend.entity_type.fields:
    - 'entity_type_id'
    - 'entity_type_code'
    - 'entity_model'
    - 'attribute_model'
    - 'entity_table'
    - 'value_table_prefix'
    - 'entity_id_field'
    - 'is_data_sharing'
    - 'data_sharing_key'
    - 'default_attribute_set_id'
    - 'increment_model'
    - 'increment_per_store'
    - 'increment_pad_length'
    - 'increment_pad_char'
    - 'additional_attribute_table'
    - 'entity_attribute_collection'

  kiboko.facebook_catalog.backend.attribute.standard.table: 'eav_attribute'
  kiboko.facebook_catalog.backend.attribute.catalog_extras.table: 'catalog_eav_attribute'
  kiboko.facebook_catalog.backend.attribute.catalog_entity.table: 'eav_entity_type'
  kiboko.facebook_catalog.backend.attribute.variant_axis.table: 'catalog_product_super_attribute'
  kiboko.facebook_catalog.backend.attribute.family.table: 'eav_attribute_set'
  kiboko.facebook_catalog.backend.attribute.standard.fields:
    - 'attribute_id'
    - 'attribute_code'
    - 'attribute_model'
    - 'backend_model'
    - 'backend_type'
    - 'backend_table'
    - 'frontend_model'
    - 'frontend_input'
    - 'frontend_label'
    - 'frontend_class'
    - 'source_model'
    - 'is_required'
    - 'is_user_defined'
    - 'default_value'
    - 'is_unique'
  kiboko.facebook_catalog.backend.attribute.catalog_extras.fields:
    - 'frontend_input_renderer'
    - 'is_global'
    - 'is_visible'
    - 'is_searchable'
    - 'is_filterable'
    - 'is_comparable'
    - 'is_visible_on_front'
    - 'is_html_allowed_on_front'
    - 'is_used_for_price_rules'
    - 'is_filterable_in_search'
    - 'used_in_product_listing'
    - 'used_for_sort_by'
    - 'is_configurable'
    - 'apply_to'
    - 'is_visible_in_advanced_search'
    - 'position'
    - 'is_wysiwyg_enabled'
    - 'is_used_for_promo_rules'

  kiboko.facebook_catalog.backend.attribute.group.table: 'eav_attribute_group'
  kiboko.facebook_catalog.backend.attribute.group.fields:
    - 'attribute_group_id'
    - 'attribute_set_id'
    - 'attribute_group_name'
    - 'sort_order'
    - 'default_id'

  kiboko.facebook_catalog.backend.attribute.label.table: 'eav_attribute_label'
  kiboko.facebook_catalog.backend.attribute.label.fields:
    - 'attribute_label_id'
    - 'attribute_id'
    - 'store_id'
    - 'value'

  kiboko.facebook_catalog.backend.attribute.option.table: 'eav_attribute_option'
  kiboko.facebook_catalog.backend.attribute.option.fields:
    - 'option_id'
    - 'attribute_id'
    - 'sort_order'

  kiboko.facebook_catalog.backend.attribute.option_value.table: 'eav_attribute_option_value'
  kiboko.facebook_catalog.backend.attribute.option_value.fields:
    - 'value_id'
    - 'option_id'
    - 'store_id'
    - 'value'

  kiboko.facebook_catalog.backend.product_attribute_value.datetime.table: 'catalog_product_entity_datetime'
  kiboko.facebook_catalog.backend.product_attribute_value.decimal.table: 'catalog_product_entity_decimal'
  kiboko.facebook_catalog.backend.product_attribute_value.integer.table: 'catalog_product_entity_integer'
  kiboko.facebook_catalog.backend.product_attribute_value.text.table: 'catalog_product_entity_text'
  kiboko.facebook_catalog.backend.product_attribute_value.varchar.table: 'catalog_product_entity_varchar'
  kiboko.facebook_catalog.backend.product_attribute_value.variant_axis.table: 'catalog_product_super_attribute'
  kiboko.facebook_catalog.backend.product_attribute_value.fields:
    - 'value_id'
    - 'entity_type_id'
    - 'attribute_id'
    - 'store_id'
    - 'entity_id'
    - 'value'

  kiboko.facebook_catalog.backend.product.table: 'catalog_product_entity'
  kiboko.facebook_catalog.backend.category_product.table: 'eav_attribute_set'
  kiboko.facebook_catalog.backend.product.fields:
    - 'entity_id'
    - 'entity_type_id'
    - 'attribute_set_id'
    - 'type_id'
    - 'sku'
    - 'has_options'
    - 'required_options'
    - 'created_at'
    - 'updated_at'

  kiboko.facebook_catalog.backend.entity_store.table: 'eav_entity_store'
  kiboko.facebook_catalog.backend.entity_store.fields:
    - 'entity_store_id'
    - 'entity_type_id'
    - 'store_id'
    - 'increment_prefix'
    - 'increment_last_id'

  kiboko.facebook_catalog.backend.family.table: 'eav_attribute_set'
  kiboko.facebook_catalog.backend.family.fields:
    - 'attribute_set_id'
    - 'entity_type_id'
    - 'attribute_set_name'
    - 'sort_order'

  kiboko.facebook_catalog.backend.product_super_attribute.table: 'catalog_product_super_attribute'
  kiboko.facebook_catalog.backend.product_super_attribute.fields:
    - 'product_super_attribute_id'
    - 'product_id'
    - 'attribute_id'
    - 'position'