parameters:
  kiboko.facebook_catalog.query_builder.family.class:                  Kiboko\Component\MagentoDriver\QueryBuilder\Doctrine\FamilyQueryBuilder
  kiboko.facebook_catalog.query_builder.product.class:                 Kiboko\Component\MagentoDriver\QueryBuilder\Doctrine\ProductQueryBuilder
  kiboko.facebook_catalog.query_builder.product_attribute.class:       Kiboko\Component\MagentoDriver\QueryBuilder\Doctrine\ProductAttributeQueryBuilder
  kiboko.facebook_catalog.query_builder.product_attribute_value.class: Kiboko\Component\MagentoDriver\QueryBuilder\Doctrine\ProductAttributeValueQueryBuilder

services:
  kiboko.facebook_catalog.query_builder.family:
    class: '%kiboko.facebook_catalog.query_builder.family.class%'
    arguments:
      - '@database_connection'
      - '%kiboko.facebook_catalog.backend.family.table%'
      - '%kiboko.facebook_catalog.backend.family.fields%'

  kiboko.facebook_catalog.query_builder.product:
    class: '%kiboko.facebook_catalog.query_builder.product.class%'
    arguments:
      - '@database_connection'
      - '%kiboko.facebook_catalog.backend.product.table%'
      - '%kiboko.facebook_catalog.backend.family.table%'
      - '%kiboko.facebook_catalog.backend.category_product.table%'
      - '%kiboko.facebook_catalog.backend.product.fields%'
      
  kiboko.facebook_catalog.query_builder.product_attribute:
    class: '%kiboko.facebook_catalog.query_builder.product_attribute.class%'
    arguments:
      - '@database_connection'
      - '%kiboko.facebook_catalog.backend.attribute.standard.table%'
      - '%kiboko.facebook_catalog.backend.attribute.catalog_extras.table%'
      - '%kiboko.facebook_catalog.backend.attribute.catalog_entity.table%'
      - '%kiboko.facebook_catalog.backend.attribute.variant_axis.table%'
      - '%kiboko.facebook_catalog.backend.attribute.family.table%'
      - '%kiboko.facebook_catalog.backend.attribute.standard.fields%'
      - '%kiboko.facebook_catalog.backend.attribute.catalog_extras.fields%'

  kiboko.facebook_catalog.query_builder.product_attribute_value.datetime:
    class: '%kiboko.facebook_catalog.query_builder.product_attribute_value.class%'
    arguments:
      - '@database_connection'
      - '%kiboko.facebook_catalog.backend.product_attribute_value.datetime.table%'
      - '%kiboko.facebook_catalog.backend.product_attribute_value.variant_axis.table%'
      - '%kiboko.facebook_catalog.backend.product_attribute_value.fields%'

  kiboko.facebook_catalog.query_builder.product_attribute_value.integer:
    class: '%kiboko.facebook_catalog.query_builder.product_attribute_value.class%'
    arguments:
      - '@database_connection'
      - '%kiboko.facebook_catalog.backend.product_attribute_value.integer.table%'
      - '%kiboko.facebook_catalog.backend.product_attribute_value.variant_axis.table%'
      - '%kiboko.facebook_catalog.backend.product_attribute_value.fields%'

  kiboko.facebook_catalog.query_builder.product_attribute_value.decimal:
    class: '%kiboko.facebook_catalog.query_builder.product_attribute_value.class%'
    arguments:
      - '@database_connection'
      - '%kiboko.facebook_catalog.backend.product_attribute_value.decimal.table%'
      - '%kiboko.facebook_catalog.backend.product_attribute_value.variant_axis.table%'
      - '%kiboko.facebook_catalog.backend.product_attribute_value.fields%'

  kiboko.facebook_catalog.query_builder.product_attribute_value.text:
    class: '%kiboko.facebook_catalog.query_builder.product_attribute_value.class%'
    arguments:
      - '@database_connection'
      - '%kiboko.facebook_catalog.backend.product_attribute_value.text.table%'
      - '%kiboko.facebook_catalog.backend.product_attribute_value.variant_axis.table%'
      - '%kiboko.facebook_catalog.backend.product_attribute_value.fields%'

  kiboko.facebook_catalog.query_builder.product_attribute_value.varchar:
    class: '%kiboko.facebook_catalog.query_builder.product_attribute_value.class%'
    arguments:
      - '@database_connection'
      - '%kiboko.facebook_catalog.backend.product_attribute_value.varchar.table%'
      - '%kiboko.facebook_catalog.backend.product_attribute_value.variant_axis.table%'
      - '%kiboko.facebook_catalog.backend.product_attribute_value.fields%'