parameters:
  kiboko.facebook_catalog.repository.doctrine.catalog_attribute.class:       Kiboko\Component\MagentoDriver\Repository\Doctrine\ProductAttributeRepository
  kiboko.facebook_catalog.repository.doctrine.family.class:                  Kiboko\Component\MagentoDriver\Repository\Doctrine\FamilyRepository
  kiboko.facebook_catalog.repository.doctrine.product_attribute.class:       Kiboko\Component\MagentoDriver\Repository\Doctrine\ProductAttributeRepository
  kiboko.facebook_catalog.repository.doctrine.product_attribute.class:       Kiboko\Component\MagentoDriver\Repository\Doctrine\CatalogAttributeRepository
  kiboko.facebook_catalog.repository.doctrine.product_attribute_value.class: Kiboko\Component\MagentoDriver\Repository\Doctrine\ProductAttributeValueRepository
  kiboko.facebook_catalog.repository.doctrine.product.class:                 Kiboko\Component\MagentoDriver\Repository\Doctrine\ProductRepository

  kiboko.facebook_catalog.repository.dummy.inventory.class:               Kiboko\Component\MagentoDriver\Repository\Dummy\ProductInventoryRepository
  kiboko.facebook_catalog.repository.dummy.url_rewrite.class:             Kiboko\Component\MagentoDriver\Repository\Dummy\ProductUrlRewriteRepository

  kiboko.facebook_catalog.repository.facade.product_attribute_value.class: Kiboko\Component\MagentoDriver\Repository\ProductAttributeValueRepositoryFacade

  kiboko.facebook_catalog.repository.cached.product_attribute.class: Kiboko\Component\MagentoDriver\Repository\CachedRepository\CachedProductAttributeRepository
  kiboko.facebook_catalog.repository.cached.family.class:            Kiboko\Component\MagentoDriver\Repository\CachedRepository\CachedFamilyRepository

services:
  kiboko.facebook_catalog.repository.doctrine.catalog_attribute:
    class: '%kiboko.facebook_catalog.repository.doctrine.catalog_attribute.class%'
    arguments:
      - '@database_connection'
      - '@kiboko.facebook_catalog.query_builder.product_attribute'

  kiboko.facebook_catalog.repository.doctrine.family:
    class: '%kiboko.facebook_catalog.repository.doctrine.family.class%'
    arguments:
      - '@database_connection'
      - '@kiboko.facebook_catalog.query_builder.family'
      - '@kiboko.facebook_catalog.factory.family'

  kiboko.facebook_catalog.repository.doctrine.product_attribute:
    class: '%kiboko.facebook_catalog.repository.doctrine.product_attribute.class%'
    arguments:
      - '@database_connection'
      - '@kiboko.facebook_catalog.query_builder.product_attribute'

  kiboko.facebook_catalog.repository.doctrine.product_attribute_value:
    class: '%kiboko.facebook_catalog.repository.doctrine.product_attribute_value.class%'
    abstract: true

  kiboko.facebook_catalog.repository.doctrine.product_attribute_value.datetime:
    parent: 'kiboko.facebook_catalog.repository.doctrine.product_attribute_value'
    arguments:
      - '@database_connection'
      - '@kiboko.facebook_catalog.query_builder.product_attribute_value.datetime'
      - '@kiboko.facebook_catalog.repository.cached.product_attribute'
      - '@kiboko.facebook_catalog.factory.product_attribute_value.datetime'
    tags:
      - { name: kiboko.facebook_catalog.repository.product_attribute_value, backend: datetime }

  kiboko.facebook_catalog.repository.doctrine.product_attribute_value.decimal:
    parent: 'kiboko.facebook_catalog.repository.doctrine.product_attribute_value'
    arguments:
      - '@database_connection'
      - '@kiboko.facebook_catalog.query_builder.product_attribute_value.decimal'
      - '@kiboko.facebook_catalog.repository.cached.product_attribute'
      - '@kiboko.facebook_catalog.factory.product_attribute_value.decimal'
    tags:
      - { name: kiboko.facebook_catalog.repository.product_attribute_value, backend: decimal }

  kiboko.facebook_catalog.repository.doctrine.product_attribute_value.integer:
    parent: 'kiboko.facebook_catalog.repository.doctrine.product_attribute_value'
    arguments:
      - '@database_connection'
      - '@kiboko.facebook_catalog.query_builder.product_attribute_value.integer'
      - '@kiboko.facebook_catalog.repository.cached.product_attribute'
      - '@kiboko.facebook_catalog.factory.product_attribute_value.integer'
    tags:
      - { name: kiboko.facebook_catalog.repository.product_attribute_value, backend: int }

  kiboko.facebook_catalog.repository.doctrine.product_attribute_value.text:
    parent: 'kiboko.facebook_catalog.repository.doctrine.product_attribute_value'
    arguments:
      - '@database_connection'
      - '@kiboko.facebook_catalog.query_builder.product_attribute_value.text'
      - '@kiboko.facebook_catalog.repository.cached.product_attribute'
      - '@kiboko.facebook_catalog.factory.product_attribute_value.text'
    tags:
      - { name: kiboko.facebook_catalog.repository.product_attribute_value, backend: text }

  kiboko.facebook_catalog.repository.doctrine.product_attribute_value.varchar:
    parent: 'kiboko.facebook_catalog.repository.doctrine.product_attribute_value'
    arguments:
      - '@database_connection'
      - '@kiboko.facebook_catalog.query_builder.product_attribute_value.varchar'
      - '@kiboko.facebook_catalog.repository.cached.product_attribute'
      - '@kiboko.facebook_catalog.factory.product_attribute_value.varchar'
    tags:
      - { name: kiboko.facebook_catalog.repository.product_attribute_value, backend: varchar }

  kiboko.facebook_catalog.repository.doctrine.product:
    class: '%kiboko.facebook_catalog.repository.doctrine.product.class%'
    arguments:
      - '@database_connection'
      - '@kiboko.facebook_catalog.query_builder.product'
      - '@kiboko.facebook_catalog.factory.product.facade'

  kiboko.facebook_catalog.repository.dummy.inventory:
    class: '%kiboko.facebook_catalog.repository.dummy.inventory.class%'
    arguments:
      - '@kiboko.facebook_catalog.repository.doctrine.product_attribute'

  kiboko.facebook_catalog.repository.dummy.url_rewrite:
    class: '%kiboko.facebook_catalog.repository.dummy.url_rewrite.class%'
    arguments:
      - '@kiboko.facebook_catalog.repository.doctrine.product_attribute'

  kiboko.facebook_catalog.repository.facade.product_attribute_value:
   class: '%kiboko.facebook_catalog.repository.facade.product_attribute_value.class%'
   arguments:
     - '@kiboko.facebook_catalog.repository.product_attribute_value.broker'

  kiboko.facebook_catalog.repository.cached.product_attribute:
    class: '%kiboko.facebook_catalog.repository.cached.product_attribute.class%'
    arguments:
      - '@kiboko.facebook_catalog.repository.doctrine.product_attribute'

  kiboko.facebook_catalog.repository.cached.family:
    class: '%kiboko.facebook_catalog.repository.cached.family.class%'
    arguments:
      - '@kiboko.facebook_catalog.repository.doctrine.family'

